title: EasyFriend's Blog
author: EasyFriend
email: lotusrock00@naver.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "Easy-Friend.github.io" # the base hostname & protocol for your site, e.g. http://example.com
description: 
  My Off-Duty Thoughts

permalink: /:slug.html

favicon: "logo.png"
goat_counter: "easy-friend"

github_username: Easy-Friend

# Build settings
theme: no-style-please

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: True # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jektex-cache


